import type { Metadata } from "next";
import { MarketingPageLayout } from "@/components/marketing/MarketingPageLayout";

export const metadata: Metadata = { title: "Acceptable Use Policy — EngageAI" };

export default function AcceptableUsePage() {
  return (
    <MarketingPageLayout
      title="Acceptable Use Policy"
      lastUpdated="4 March 2025"
    >
      <h2>1. Prohibited uses</h2>
      <p>You may not use EngageAI to:</p>
      <ul>
        <li>
          Send <strong>spam</strong>, unsolicited bulk messages, or repetitive
          replies across accounts.
        </li>
        <li>
          <strong>Harass, threaten, or abuse</strong> other users or commenters.
        </li>
        <li>
          <strong>Impersonate</strong> another person, brand, or organisation.
        </li>
        <li>
          Post or distribute <strong>illegal content</strong>, including content
          that infringes intellectual-property rights.
        </li>
        <li>
          Attempt to <strong>circumvent rate limits</strong> or platform terms of
          service using automation features.
        </li>
        <li>
          Use the Service to generate or distribute{" "}
          <strong>misinformation</strong> or deliberately misleading content.
        </li>
      </ul>

      <h2>2. Responsibility for AI-generated content</h2>
      <p>
        AI-generated reply drafts are suggestions. You are solely responsible
        for any content you choose to post on social-media platforms, whether
        generated by the AI, edited by you, or written manually.
      </p>

      <h2>3. Automation limits</h2>
      <p>
        Automation features (auto-send replies, follower actions) are subject to
        per-day caps configured in your settings. You must not attempt to bypass
        these limits through multiple accounts or other means.
      </p>

      <h2>4. Consequences</h2>
      <p>
        Violations of this policy may result in temporary suspension or permanent
        termination of your account. We will provide notice and an opportunity
        to respond where practicable, except in cases of severe or repeated
        violations.
      </p>
    </MarketingPageLayout>
  );
}
